# File: .github/workflows/render-readme.yml
name: Render README.Rmd

# When to run
on:
  push:
    # if changes occur on any branch for these files
    branches:
      - "**"
    paths:
      - "README.Rmd"
      - ".github/workflows/render-readme.yaml"

  workflow_dispatch:    # also allow manual runs from the Actions tab

permissions:
  contents: write

jobs:
  render-README:
    runs-on: ubuntu-latest
    container:
      image: rocker/verse:latest

    steps:
      # 1) Which actions to use
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # 👈 Enables authenticated push

      # 2) Install system dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libfontconfig1-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libfreetype6-dev \
            libpng-dev \
            libtiff5-dev \
            libjpeg-dev
      
      # 3) Extract version from tag
      - name: Extract version from tag and update DESCRIPTION
        id: version
        shell: bash
        run: |
          # the version is set to 0.0.0 if there is no tag
          VERSION=${GITHUB_REF#refs/tags/v}
          if [[ "$VERSION" == "$GITHUB_REF" || -z "$VERSION" ]]; then
              VERSION="0.0.0"
          fi

          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=$GITHUB_REF_NAME" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"
      
      # 4) Generate DESCRIPTION from tag and template
      - name: Generate DESCRIPTION from tag and template
        shell: bash
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            cp DESCRIPTION-template DESCRIPTION
          else
            mv DESCRIPTION-template DESCRIPTION
          fi
          VERSION="${{ steps.version.outputs.version }}"
          Rscript -e "install.packages('desc', repos = 'https://cloud.r-project.org/'); desc::desc_set_version('$VERSION')"

      # 5) Install R dependencies
      - name: Install dependencies
        run: |
          Rscript  -e "devtools::install_deps('.', dependencies = TRUE)"

      # 6) Install R dependencies
      - name: Install package
        run: |
          Rscript  -e "devtools::install('.', build_vignettes = FALSE)"

      # 7) Knit the README
      - name: Render README.Rmd → README.md
        run: |
          Rscript -e "rmarkdown::render('README.Rmd', output_format='md_document',
                                          output_options = list(variant = 'markdown_github'))"

      # 8) Commit & push back if README.md changed
      - name: Commit rendered README.md
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add README.md
          git commit -m "Re-render README" || echo "No changes to commit"
          git push origin HEAD:${GITHUB_REF#refs/heads/}

