# File: .github/workflows/render-readme.yml
name: Render README.Rmd

# When to run
on:
  push:
    # if changes occur on any branch for these files
    branches:
      - "**"
    paths:
      - "README.Rmd"
      - ".github/workflows/render-readme.yml"

  pull_request:
    branches: [main, master]

  workflow_dispatch:    # also allow manual runs from the Actions tab

permissions:
  contents: write

jobs:
  render-README:
    runs-on: ubuntu-latest
    container:
      image: rocker/verse:latest

    steps:
      # 1) Which actions to use
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # 👈 Enables authenticated push

      # 2) Install system dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libfontconfig1-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libfreetype6-dev \
            libpng-dev \
            libtiff5-dev \
            libjpeg-dev

      # 3) Install R dependencies
      - name: Install dependencies
        run: |
          Rscript  -e "devtools::install_deps('.', dependencies = TRUE)"

      # 4) Install R dependencies
      - name: Install package
        run: |
          Rscript  -e "devtools::install('.', build_vignettes = FALSE)"

      # 5) Knit the README
      - name: Render README.Rmd → README.md
        run: |
          Rscript -e "rmarkdown::render('README.Rmd', output_format='md_document',
                                          output_options = list(variant = 'markdown_github'))"

      # 6) Commit & push back if README.md changed
      - name: Commit rendered README.md
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add README.md
          git commit -m "Re-render README" || echo "No changes to commit"
          git push origin HEAD:${GITHUB_REF#refs/heads/}

