# File: .github/workflows/render-readme.yml
name: Render README.Rmd

# When to run
on:
  push:
    # only when Rmd or workflow itself changes:
    paths:
      - README.Rmd
      - .github/workflows/render-readme.yml
    branches: [main, master]
 
  pull_request:
    branches: [main, master]
    
  workflow_dispatch:    # also allow manual runs from the Actions tab

jobs:
  render-README:
    runs-on: ubuntu-latest
    
    steps:
      # 1) Which actions to use
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
      
      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v3

      # 2) Install system dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libfontconfig1-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libfreetype6-dev \
            libpng-dev \
            libtiff5-dev \
            libjpeg-dev

      # 3) Install some of the million pieces source from the cheapest supplier
      - name: Install dependencies
        run: |
          R -e "install.packages(c('knitr','rmarkdown'), repos='https://cloud.r-project.org')"
          
      # 4) Knit the README
      - name: Render README.Rmd → README.md
        run: |
          R -e "rmarkdown::render('README.Rmd', output_format='md_document',
                                          output_options = list(variant = 'markdown_github'))"

      # 5) Commit & push back if README.md changed
      - name: Commit & Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "ci: auto-render README.md from README.Rmd"
          file_pattern: README.md
          # optionally set a user/email:
          # author_name: github-actions
          # author_email: actions@github.com
   
