# File: .github/workflows/render-readme.yml
name: Render README.Rmd

on:
  push:
    paths:
      - README.Rmd
      - .github/workflows/render-readme.yml
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Set up R (includes a compatible Pandoc, but we’ll still add setup-pandoc below)
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3'       # or whichever R version you need

      # 3) (Recommended) Explicitly install a recent Pandoc binary
      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v3

      # 4) Cache R package library (optional, but speeds CI)
      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/*.Rproj','**/*.lock') }}
          restore-keys: |
            ${{ runner.os }}-r-

      # 5) Install any R packages you need
      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages(c("knitr","rmarkdown"), repos="https://cloud.r-project.org")'
          # If your README.Rmd also uses other packages, install them here; e.g.:
          # Rscript -e 'install.packages(c("dplyr","readr"))'

      # 6) Render the README.Rmd into README.md
      - name: Render README.Rmd → README.md
        run: |
          Rscript -e 'rmarkdown::render(
                        input = "README.Rmd",
                        output_format = "md_document",
                        output_options = list(variant = "markdown_github")
                      )'

      # 7) Commit & push back if README.md was modified
      - name: Commit & Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "ci: auto-render README.md from README.Rmd"
          file_pattern: README.md
