name: R-unit-tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch: # also allow manual runs from the Actions tab

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    container:
      image: rocker/verse:latest  # Includes R, RMarkdown, tidyverse, etc.

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libfontconfig1-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libfreetype6-dev \
            libpng-dev \
            libtiff5-dev \
            libjpeg-dev
      
      - name: Extract version from tag and update DESCRIPTION
        id: version
        shell: bash
        run: |
          # the version is set to 0.0.0 if there is no tag
          VERSION=${GITHUB_REF#refs/tags/v}
          if [[ "$VERSION" == "$GITHUB_REF" || -z "$VERSION" ]]; then
              VERSION="0.0.0"
          fi

          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=$GITHUB_REF_NAME" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"
      
      - name: Generate DESCRIPTION from tag and template
        shell: bash
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            cp DESCRIPTION-template DESCRIPTION
          else
            mv DESCRIPTION-template DESCRIPTION
          fi
          VERSION="${{ steps.version.outputs.version }}"
          Rscript -e "install.packages('desc', repos = 'https://cloud.r-project.org/'); desc::desc_set_version('$VERSION')"

      - name: Install dependencies
        run: |
          Rscript -e "devtools::install_deps(dependencies = TRUE)"

      - name: Run tests
        run: |
          Rscript -e "devtools::test()"
